protected/modules/ad/models/Stat.php
<?php

/**
 * This is the model class for table "stat".
 *
 * The followings are the available columns in table 'stat':
 * @property string $adid
 * @property string $date
 * @property string $hits
 * @property string $clicks
 * @property string $likes
 * @property string $statid
 */
class Stat extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'stat';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('adid', 'required'),
			array('adid', 'length', 'max'=>6),
			array('hits, clicks, likes', 'length', 'max'=>8),
			array('date', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('adid, date, hits, clicks, likes, statid', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'adid' => 'Adid',
			'date' => 'Date',
			'hits' => 'Hits',
			'clicks' => 'Clicks',
			'likes' => 'Likes',
			'statid' => 'Statid',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('adid',$this->adid,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('hits',$this->hits,true);
		$criteria->compare('clicks',$this->clicks,true);
		$criteria->compare('likes',$this->likes,true);
		$criteria->compare('statid',$this->statid,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * @return CDbConnection the database connection used for this class
	 */
	public function getDbConnection()
	{
		return Yii::app()->mysql;
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Stat the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/modules/ad/controllers/AdController.php
<?php

/**
 * 	@author  Karlos Álvarez <info@weird.is>
 * 
 * 	AdController
 * 
 * 	Manages PHP Ad Manager modified to meet this project.
 * 
 *  Original PHP Ad Manager sources:
 *  http://admgr.sourceforge.net/
 * 
 *  Contact:
 *  Email: development@digitekdesign.com
 * 
 *  Some commnads:
 * 
 *  ALTER TABLE ads ADD cssad  VARCHAR(4096) NOT NULL DEFAULT '' AFTER htmlad;
 *  ALTER TABLE ads ADD uri VARCHAR(256) NOT NULL DEFAULT '' AFTER title;
 *  ALTER TABLE ads ADD domainid INT(6) ZEROFILL DEFAULT 0 AFTER groupid;
 *  ALTER TABLE ads ADD uid SMALLINT ZEROFILL AFTER adid;
 *  ALTER TABLE ads MODIFY title VARCHAR(192) DEFAULT NULL;
 * 
 * 	ALTER TABLE ads DROP COLUMN classid;
 * 
 */

Yii::import("application.helpers.*");

class AdController extends Controller { 

	protected $apiContext;
	protected $sandBoxId;
	protected $sandBoxSecret;

	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2b';

	public $defaultAction = 'index';

	public function init() {

	}

	public static function renderAd( $ad ) {

		// print_r($ad); die;
		$txt= ( isset($ad->textad) ) ? $ad->textad : $ad->title;
		$w=   ( isset($ad->width) )  ? $ad->width."px" : '500px';
		$h=   ( isset($ad->height) ) ? $ad->height."px" : '300px';

		if( isset( $ad->htmlad ) ) {
			//$adstr = '<link href="/css/styles.css" rel="stylesheet" type="text/css" media="screen" />'.
			$adstr = '<div style="width:500px; height:300px; display:inline-block; vertical-align: top;">'.  $ad->htmlad .'</div>';
			$css = (array) json_decode($ad->cssad);
			//echo $ad->htmlad;
			//echo $adstr;
			//echo $css['img']->src;
			//
			if( isset( $css['img']->src )  )
				$adstr = str_replace("src", "src=\"". $css['img']->src . "\"", $adstr);
			
			echo $adstr; 
			return;
		}
		else
			$adstr = "ERROR";

        return $adstr;
	}

	/**
	 * @return array action filters
	 */
	public function filters() {
		return array(
			/*
			
			array( 
				'HttpAuthFilter - rest',
			),
			*/
		
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
			
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules() {
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('rest'),
				'expression' => array('HttpAuthController','auth')
				
			),
			array('allow', // allow authenticated user to perform 'create', 'update' actions, 'admin' is secure also
				'actions'=>array('create','update','stats','activate','delete'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform and 'delete' actions
				'actions'=>array('view', 'admin'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionStats($id) {

		$criteria = new CDbCriteria;
		$criteria->condition = 'adid='.$id;

		$res = Stat::model()->find($criteria);
		//echo "hello";
		//print_r($res); die;

		$this->render('ad.views.stat.index',array(
			//'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionActivate($id) {

		$this->render('activate',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('index',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Ad;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Ad'])) {

			$model->attributes=$_POST['Ad'];
			if( $model->save() )
				$this->redirect(array('view','id'=>$model->adid));
		}

		$this->render('create',array(
			'model'=>$model,
		));

	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Ad']))
		{
			$model->attributes=$_POST['Ad'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->adid));
		}
		if(UserModule::isAdmin())
			$this->render('update',array(
				'model'=>$model,
			));
		else
			$this->render('edit',array(
				'model'=>$model,
			));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}


	/**
	 * Rest
	 * 
	 * Accepts requests from js actions
	 * HTTP_BASIC_AUTH needed to access this method
	 * @see HttpAuthController
	 * 
	 * Rest action identifieds
	 * [all]
	 * 	Retrieve data of non expired ads
	 * [geo]
	 * 	Appends geolocated data from user's map requests
	 * [click]
	 *  Validates unique click and Updates click data 
	 * 
	 *  @version 1.3.2
	 */
	public function actionRest($com) { 
		
		/**
		 * @abstract 1.3.1
		 * Errors executing model Ad::model()->findAll() with many criteria elements
		 * Used as --> Yii::app()->mysql->createCommand(
		 * 
		 * @abstract 1.3.2
		 *  - Can update it using Ad::model(). Code is using command as model actions no really needed.
		 *  - Code is working perfect
		 */
		switch( strtolower($com) ) {
			
			// Get all active ads
			case 'all': { 
				$names=[];
				$command= Yii::app()->mysql->createCommand("select uri,title,address,zip,lat,lng,htmlad,hash from ads where expiredate > '".date('Y-m-d H:i:s', time() )."'");
				$reader=$command->query();
				foreach($reader as $row) {
					$names[]=$row;
				}
				echo json_encode($names);
			} break;

			// Request to save Geolocate address data 
			case 'geo': { 
				if( !isset($_POST['data']) )
					return;

				$count=0;
				$arr = json_decode( $_POST['data'] );
				if( !$arr ) {
					echo json_encode(array('error'=>'decoding json error'));
					return;
				}
				foreach ($arr as $obj) {
					// print_r($obj); die;
					if( isset($obj->hash) && isset($obj->lat) && isset($obj->lng) ) {
						$command= Yii::app()->mysql->createCommand("update ads set lat='".$obj->lat."', lng='".$obj->lng."' where hash='".$obj->hash."'");
						$result = $command->execute();
						if( $result >= 1 ) {
							Yii::log('Updated lat lng in '.$obj->address, 'info');
							$count+=1;
						} //elseif( $result == 0) {
						//Yii::log('Already Updated lat lng in '.$obj->address, 'info');
					}
				}

				echo json_encode(array('updated'=>$count));
			} break;

			// Track ad click
			// One click per sessionId, ad
			// One click per user agent, ip, day, ad
			
			case 'click': { 
				if( !isset($_POST['hash']) )
					return;

				$h =  $_POST['hash'];
				$ua = $_POST['ua'];
				$ip = $_POST['i'];
				$sessionId = $_POST['s'];

				if( $sessionId !== session_id() ) {
					Yii::log("Possible xss in $ip","info");
					return;
				}

				$command= Yii::app()->mysql->createCommand("select * from dayclicks where sui='".$sessionId."' and adhash='".$h."'");
				$n=$command->execute();
				if( $n > 0) 
					return;

				$command= Yii::app()->mysql->createCommand("select * from dayclicks where agent='".$ua."' and day='".date("Ymd", time())."' and ip='".$ip."' and adhash='".$h."'");
				$n=$command->execute();
				if( $n > 0 ) 
					return;

				$command= Yii::app()->mysql->createCommand("insert into dayclicks set sui='".$sessionId."', day='".date("Ymd", time())."', agent='".$ua."', ip='".$ip."', adhash='".$h."' ");
				$command->execute();

				$command= Yii::app()->mysql->createCommand("update ads set clicks=clicks+1 where hash=".$h."");
				$result = $command->execute();

				echo json_encode(array('updated'=> ($result>=1) ? true:false ));
			} break;
		}
		
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex() {

		/*		
		if( UserModule::isAdmin() )
			$dataProvider=new CActiveDataProvider('Ad');
		else {
			//Get the key
			$user = UserModule::user(Yii::app()->user->id);
			$id = $user->id;

			$criteria=new CDbCriteria( array(                    
	            'order'=>'createdate desc',
	            // Can do an alias for the table
	            // 'with' => array('userToProject'=>array('alias'=>'user')),
	            'condition'=>"uid='".$id."'"
	        ));

			$dataProvider=new CActiveDataProvider('Ad', array(
			    'criteria'=>$criteria,
			) );
		}
		
		$this->render('ad.views.ad.index',array(
			'dataProvider'=>$dataProvider,
		));
		*/
	
		$model=new Ad('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Ad']))
			$model->attributes=$_GET['Ad'];

		$this->render('index',array(
			'model'=>$model,
			//'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Ad('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Ad']))
			$model->attributes=$_GET['Ad'];

protected/modules/ad/controllers/StatController.php
<?php

class StatController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Stat;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Stat']))
		{
			$model->attributes=$_POST['Stat'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->statid));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Stat']))
		{
			$model->attributes=$_POST['Stat'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->statid));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		// $dataProvider=new CActiveDataProvider('Stat');
		$this->render('index',array(
			//'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Stat('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Stat']))
			$model->attributes=$_GET['Stat'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Stat the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Stat::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Stat $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='stat-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/modules/ad/views/stat/_form.php
<?php
/* @var $this StatController */
/* @var $model Stat */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'stat-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'statid'); ?>
		<?php echo $form->textField($model,'statid',array('size'=>6,'maxlength'=>6)); ?>
		<?php echo $form->error($model,'statid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'adid'); ?>
		<?php echo $form->textField($model,'adid',array('size'=>6,'maxlength'=>6)); ?>
		<?php echo $form->error($model,'adid'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'date'); ?>
		<?php echo $form->textField($model,'date'); ?>
		<?php echo $form->error($model,'date'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'hits'); ?>
		<?php echo $form->textField($model,'hits',array('size'=>8,'maxlength'=>8)); ?>
		<?php echo $form->error($model,'hits'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'clicks'); ?>
		<?php echo $form->textField($model,'clicks',array('size'=>8,'maxlength'=>8)); ?>
		<?php echo $form->error($model,'clicks'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'likes'); ?>
		<?php echo $form->textField($model,'likes',array('size'=>8,'maxlength'=>8)); ?>
		<?php echo $form->error($model,'likes'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/modules/ad/views/stat/_search.php
<?php
/* @var $this StatController */
/* @var $model Stat */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'statid'); ?>
		<?php echo $form->textField($model,'statid',array('size'=>6,'maxlength'=>6)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'adid'); ?>
		<?php echo $form->textField($model,'adid',array('size'=>6,'maxlength'=>6)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'date'); ?>
		<?php echo $form->textField($model,'date'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hits'); ?>
		<?php echo $form->textField($model,'hits',array('size'=>8,'maxlength'=>8)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'clicks'); ?>
		<?php echo $form->textField($model,'clicks',array('size'=>8,'maxlength'=>8)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'likes'); ?>
		<?php echo $form->textField($model,'likes',array('size'=>8,'maxlength'=>8)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/ad/views/stat/_view.php
<?php
/* @var $this StatController */
/* @var $data Stat */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('statid')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->statid), array('view', 'id'=>$data->statid)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('adid')); ?>:</b>
	<?php echo CHtml::encode($data->adid); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('date')); ?>:</b>
	<?php echo CHtml::encode($data->date); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('hits')); ?>:</b>
	<?php echo CHtml::encode($data->hits); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('clicks')); ?>:</b>
	<?php echo CHtml::encode($data->clicks); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('likes')); ?>:</b>
	<?php echo CHtml::encode($data->likes); ?>
	<br />


</div>

protected/modules/ad/views/stat/create.php
<?php
/* @var $this StatController */
/* @var $model Stat */

$this->breadcrumbs=array(
	'Stats'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Stat', 'url'=>array('index')),
	array('label'=>'Manage Stat', 'url'=>array('admin')),
);
?>

<h1>Create Stat</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/modules/ad/views/stat/index.php
<?php
/* @var $this StatController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Stats',
);

$this->menu=array(
	//array('label'=>'Create Stat', 'url'=>array('create')),
	//array('label'=>'Manage Stat', 'url'=>array('admin')),
	array('label'=>'Back', 'url'=>array('ad/index'))
);



?>


<h3>Stats</h3>

<?php 
/*

 $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); */ ?>

<div class='options'> <span class="option">Hits</span> | <span class="option">Clicks</span> | <span class="option">Likes</span> </div>
<canvas id="myChart" width="300" height="180"></canvas>
<script src="/js/jquery-1.12.3.js" type="text/javascript"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
<script>
var myChart;
var ctx = document.getElementById("myChart");
var json = '[{"hits":3,"clicks":1,"likes":0,"ts":1462827540000},{"hits":5,"clicks":3,"likes":0,"ts":1463227540000},{"hits":8,"clicks":4,"likes":1,"ts":1464227540000},{"hits":9,"clicks":5,"likes":2,"ts":1464827540000},{"hits":10,"clicks":7,"likes":3,"ts":1465227540000},{"hits":15,"clicks":8,"likes":4,"ts":1465827540000}]';

var obj = JSON.parse(json);
console.log(new Date().getTime());



function drawSelection(selection) {
	var data=[], labels=[], dt, hits=[], likes=[];
	for (var i in obj ) {

		hits.push(obj[i].hits);
		likes.push(obj[i].likes);
		data.push(obj[i].clicks);
		dt=new Date(obj[i].ts);

		labels.push( dt.toDateString() );
	}

	myChart = new Chart(ctx, {
	    type: 'line',
	    data: {
	        labels: labels,
	        datasets: [
	        	{
		            label: ' Hits',
		            data: hits,
		            backgroundColor: "rgba(220,20,220,0.2)",
	    			strokeColor: "rgba(220,20,220,1)",
	    			fontColor: "rgba(100,120,100,1)",
	    			borderColor: "rgba(100,120,100,1)",

		            /*backgroundColor: [
		                'rgba(255, 99, 132, 0.2)',
		                'rgba(54, 162, 235, 0.2)',
		                'rgba(255, 206, 86, 0.2)',
		                'rgba(75, 192, 192, 0.2)',
		                'rgba(153, 102, 255, 0.2)',
		                'rgba(255, 159, 64, 0.2)'
		            ],
		            borderColor: [
		                'rgba(255,99,132,1)',
		                'rgba(54, 162, 235, 1)',
		                'rgba(255, 206, 86, 1)',
		                'rgba(75, 192, 192, 1)',
		                'rgba(153, 102, 255, 1)',
		                'rgba(255, 159, 64, 1)'
		            ],*/
		            borderWidth: 1
		        },
		        {
		            label: ' Clicks',
		            data: data,
		            backgroundColor: "rgba(54, 162, 235, 0.2)",
	    			strokeColor: "rgba(54, 162, 235, 0.2)",
	    			fontColor: "rgba(54, 162, 235, 1)",
	    			borderColor: "rgba(54, 162, 235, 1)",
		            borderWidth: 1
		        },
		        {
		            label: ' Likes',
		            data: likes,
		            backgroundColor: 'rgba(255, 159, 64, 0.6)',
		            borderColor: 'rgba(255, 159, 64, 1)',
		            borderWidth: 1
		        }
	        ]
	    },
	    options: {
	        scales: {
	            yAxes: [{
	                ticks: {
	                    beginAtZero:true
	                }
	            }]
	        },
	        /*
	        legend: {
	            display: true,
	            labels: {
	                fontColor: 'rgb(255, 99, 132)'
	            }
	        }*/
	    }
	});
}

$(document).ready(function(){ 

	console.log("Document ready");
	
	var defaultMode='hits';
	drawSelection(defaultMode);

	$('.option').on('click', function(){
		drawSelection( $(this).html().toLowerCase() );
	});
});

</script>